### ISSUE TITLE
[Bug] Speedtest-Tracker widget doesn't work 

### ISSUE THREAD

**Issue by LLinoor** [benphelps/homepage#740]
### Description

My Speedtest-Tracker widget doesn't work correctly as you can see:

![Screenshot 2022-12-28 185105](https://user-images.githubusercontent.com/48157029/209852596-7c506826-d514-4bb2-8809-c83cb95db076.png)

I looked at the logs to see what's wrong and found this:
```
[2022-12-28T17:10:45.656Z] error: <httpProxy> Error calling http://192.168.1.14/api/speedtest/latest...
[2022-12-28T17:10:45.657Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.1.14:8765
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.14',
    port: 8765
  }
]
```

Here is my config : 
```
- Speedtest:
        icon: speedtest-tracker
        href: http://192.168.1.14:8765
        description: Speedtest tracking
        server: docker
        container: speedtest
        widget:
            type: speedtest
            url: http://192.168.1.14:8765
```

I found a temporary solution, I exposed Speedtest-Tracker on my nginx server and I changed my services.yaml file so that it fetches the data from nginx.
```
widget:
     type: speedtest
     url: http://lilian.io/speedtest/
```
With this, I was able to get my download speeds, ...

![Screenshot 2022-12-28 190208](https://user-images.githubusercontent.com/48157029/209853772-bb6cf151-7e76-4a93-8c66-676294624e93.png)

But I'm still stuck because I have to keep my Speedtest-Tracker exposed, which bothers me.
I can't figure out what the problem is :(

### Steps to reproduce

1. Configure the Speedtest-Tracker widget
2. Observe that it does not work

### homepage version

v0.5.7 (9f63a5a, Dec 26, 2022)

### Installation method

Docker

### Container Logs

already provided

### Browser Logs

nothing

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
