### ISSUE TITLE
[Bug] speedtest tracker widget reporting a fixed value not the lastes

### ISSUE THREAD

**Issue by spupuz** [benphelps/homepage#846]
### Description

![image](https://user-images.githubusercontent.com/1721792/213373745-03c9137e-f545-421f-8d5b-1d5789809027.png)

but the latest result is:

![image](https://user-images.githubusercontent.com/1721792/213373809-2c24e27c-4f40-4648-bddb-e6e9f17a5b3b.png)

seems stuck

### Steps to reproduce

don't know how to reproduce.

### homepage version

v0.5.10 (e1799f1, Jan 7, 2023)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Those look identical, with some rounding...

But also, we pull this directly from the speedtest api endpoint `speedtest/latest` so not any issue here I dont think

**Comment by spupuz** [comment]
yeah i miss the rounded probably! my fault
